### PR TITLE
Update getSiteStats.php

### PR DESCRIPTION
**Pull request by sinnatrix**

### CODE REVIEW

**Comment by steffanjensen** [comment]
why is this method better?

**Comment by sinnatrix** [comment]
its not better method it doesnt worked for me it didnt show no pool stats for me maybe i did something wrong but like this its working good check my website i made bytecoin.gq

**Comment by steffanjensen** [comment]
okay that is not an issue maybe your config is in a wrong folder or edited wrong. The problem with Getsitestats and gettopminers is when you have around 10/20 loyal users the api request takes to long.

**Comment by sinnatrix** [comment]
i didnt do nothing wrong i just git cloned i use xampp i chaned the config i did the miner site key private key everything it didnt show me the stats maybe u should try to git clone if it works for you or not or myabe its not issue at all dont know just trying 2 help here coz its nice project you have

**Comment by steffanjensen** [comment]
what version of php do you run? I have seen that have an effect on the getSiteStats and GetTopMiners ?

**Comment by sinnatrix** [comment]
php 7

**Comment by steffanjensen** [comment]
I had the same issue as you, I know this sound silly but how i got around is was changing the path from /api/ to /

**Comment by gexxxter** [comment]
Sorry I don´t see any benefits

**Pull request closed without merging**
