### PR TITLE
Update collectBalance.php

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by steffanjensen** [comment]
Call to undefined method mysqli_stmt::get_result() Fatal error: collectBalance.php on line 6

**Comment by ghost** [comment]
Aww, yeah. This is mysqlnd specific. Will fix that asap.

**Comment by ghost** [comment]
Done.

**Review by steffanjensen — APPROVED** [review]

**Review by gexxxter — APPROVED** [review]
much appreciated!

**Pull request merged**
